name: CI

on:
  push:
    branches: [ master ]


jobs:
  buildx:
    runs-on: [self-hosted, linux, ARM64]
    #runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #- name: Set up Docker Buildx
      #  id: buildx
      #  uses: crazy-max/ghaction-docker-buildx@v3
      #  with:
      #    buildx-version: latest
      #    qemu-version: latest
      #- name: Available platforms
      #  run: echo ${{ steps.buildx.outputs.platforms }}
      #- name: build amd64
      #  run: |
      #    docker buildx build \
      #      --platform linux/amd64 \
      #      --output "type=image,push=false" \
      #      --file ./Dockerfile .
      - name: build arm64
        run: |
          docker build .
